import { Transaction, Budget, Alert, UserProfile, AdminUser, AdminCategory, AdminTransaction } from "./types";

export const DEFAULT_TRANSACTIONS: Transaction[] = [
  {
    id: "tx-001",
    merchant: "Mamak Corner",
    amount: 12.5,
    date: "2025-06-02",
    category: "Food & Dining",
    notes: "Nasi Lemak + Teh Tarik with friends",
    source: "manual",
  },
  {
    id: "tx-002",
    merchant: "RapidKL LRT",
    amount: 4.5,
    date: "2025-06-03",
    category: "Transport",
    notes: "Commute to internship",
    source: "manual",
  },
  {
    id: "tx-003",
    merchant: "Popular Bookstore",
    amount: 45.0,
    date: "2025-06-05",
    category: "Shopping",
    notes: "Reference books for KD34603 module",
    source: "manual",
  },
  {
    id: "tx-004",
    merchant: "Digi Telecommunications",
    amount: 35.0,
    date: "2025-06-06",
    category: "Bills",
    notes: "Monthly prepaid internet package",
    source: "manual",
  },
  {
    id: "tx-005",
    merchant: "GSC Cinema",
    amount: 22.0,
    date: "2025-06-08",
    category: "Entertainment",
    notes: "Movie ticket with classmates",
    source: "manual",
  },
  {
    id: "tx-006",
    merchant: "Grab Car",
    amount: 15.0,
    date: "2025-06-10",
    category: "Transport",
    notes: "Ride back from campus in rain",
    source: "manual",
  },
  {
    id: "tx-007",
    merchant: "UMS Food Court",
    amount: 8.5,
    date: "2025-06-12",
    category: "Food & Dining",
    notes: "Economy Rice",
    source: "manual",
  },
  {
    id: "tx-008",
    merchant: "Coop Library Print",
    amount: 5.0,
    date: "2025-06-14",
    category: "Other",
    notes: "Printing FYP proposal",
    source: "manual",
  },
  {
    id: "tx-009",
    merchant: "Guardian Pharmacy",
    amount: 42.1,
    date: "2025-06-15",
    category: "Shopping",
    notes: "Vitamins and hygiene supplies",
    source: "ocr",
  },
  {
    id: "tx-010",
    merchant: "Tealive",
    amount: 14.0,
    date: "2025-06-16",
    category: "Food & Dining",
    notes: "Signature Brown Sugar Pearl Milk Tea",
    source: "manual",
  },
  {
    id: "tx-011",
    merchant: "Kopi Kebun",
    amount: 18.0,
    date: "2025-06-17",
    category: "Food & Dining",
    notes: "Iced Latte study session",
    source: "manual",
  },
  {
    id: "tx-012",
    merchant: "Campus Shuttle",
    amount: 2.0,
    date: "2025-06-18",
    category: "Transport",
    notes: "Bus fare to UMS Main Hall",
    source: "manual",
  },
];

export const DEFAULT_BUDGETS: Budget = {
  "Food & Dining": 300.0,
  Transport: 100.0,
  Shopping: 150.0,
  Bills: 60.0,
  Entertainment: 80.0,
  Other: 50.0,
};

export const DEFAULT_ALERTS: Alert[] = [
  {
    id: "al-101",
    type: "Unusual Spike",
    category: "Shopping",
    amount: 120.0,
    date: "2025-06-01",
    severity: "High",
    dismissed: false,
  },
  {
    id: "al-102",
    type: "Overspend Warning",
    category: "Food & Dining",
    amount: 45.0,
    date: "2025-06-11",
    severity: "Medium",
    dismissed: false,
  },
];

export const DEFAULT_PROFILE: UserProfile = {
  name: "Amirul Syafiq",
  university: "Universiti Malaysia Sabah",
  studentId: "BI23100011",
  age: 21,
  allowanceRange: "RM500-RM1000",
};

export const DEFAULT_ADMIN_USERS: AdminUser[] = [
  {
    userId: "U1001",
    name: "Amirul Syafiq",
    institution: "Universiti Malaysia Sabah",
    age: 21,
    plan: "Pro",
    active: true,
    registeredDate: "2025-01-10",
    totalTransactions: 12,
  },
  {
    userId: "U1002",
    name: "Siti Aminah",
    institution: "Universiti Malaya",
    age: 22,
    plan: "Free",
    active: true,
    registeredDate: "2025-02-14",
    totalTransactions: 8,
  },
  {
    userId: "U1003",
    name: "Teoh Wei Jie",
    institution: "Universiti Sains Malaysia",
    age: 20,
    plan: "Pro",
    active: false,
    registeredDate: "2025-03-05",
    totalTransactions: 24,
  },
  {
    userId: "U1004",
    name: "Arun Kumar",
    institution: "Universiti Teknologi Malaysia",
    age: 23,
    plan: "Free",
    active: true,
    registeredDate: "2025-04-18",
    totalTransactions: 12,
  },
  {
    userId: "U1005",
    name: "Nurul Izzah",
    institution: "Universiti Malaysia Sarawak",
    age: 21,
    plan: "Pro",
    active: true,
    registeredDate: "2025-05-22",
    totalTransactions: 3,
  },
];

export const DEFAULT_ADMIN_CATEGORIES: AdminCategory[] = [
  { categoryName: "Food & Dining", colour: "#FFA07A", default: true, active: true },
  { categoryName: "Transport", colour: "#87CEFA", default: true, active: true },
  { categoryName: "Shopping", colour: "#DA70D6", default: true, active: true },
  { categoryName: "Bills", colour: "#FFD700", default: true, active: true },
  { categoryName: "Entertainment", colour: "#ADFF2F", default: true, active: true },
  { categoryName: "Other", colour: "#D3D3D3", default: true, active: true },
];

export const DEFAULT_ADMIN_TRANSACTIONS: AdminTransaction[] = [
  {
    id: "TXN-2025-001",
    user: "Siti Aminah",
    merchant: "RapidKL LRT",
    category: "Transport",
    amount: 4.5,
    date: "2025-06-02",
    source: "manual",
    flagged: false,
  },
  {
    id: "TXN-2025-002",
    user: "Siti Aminah",
    merchant: "Guardian Pharmacy",
    category: "Shopping",
    amount: 42.1,
    date: "2025-06-03",
    source: "ocr",
    flagged: false,
  },
  {
    id: "TXN-2025-003",
    user: "Siti Aminah",
    merchant: "Mamak Corner",
    category: "Food & Dining",
    amount: 15.6,
    date: "2025-06-05",
    source: "manual",
    flagged: false,
  },
  {
    id: "TXN-2025-004",
    user: "Teoh Wei Jie",
    merchant: "Steam Games Store",
    category: "Entertainment",
    amount: 120.0,
    date: "2025-06-01",
    source: "manual",
    flagged: true,
  },
  {
    id: "TXN-2025-005",
    user: "Teoh Wei Jie",
    merchant: "Grab Food",
    category: "Food & Dining",
    amount: 34.5,
    date: "2025-06-04",
    source: "ocr",
    flagged: false,
  },
  {
    id: "TXN-2025-006",
    user: "Teoh Wei Jie",
    merchant: "Digi Telecommunications",
    category: "Bills",
    amount: 50.0,
    date: "2025-06-06",
    source: "manual",
    flagged: false,
  },
  {
    id: "TXN-2025-007",
    user: "Arun Kumar",
    merchant: "Shell Petrol",
    category: "Transport",
    amount: 40.0,
    date: "2025-06-08",
    source: "manual",
    flagged: false,
  },
  {
    id: "TXN-2025-008",
    user: "Arun Kumar",
    merchant: "Giant Hypermarket",
    category: "Shopping",
    amount: 115.3,
    date: "2025-06-11",
    source: "ocr",
    flagged: false,
  },
];

export const HISTORICAL_SPENDING = [
  { month: "April", actual: 710, budget: 740 },
  { month: "May", actual: 740, budget: 740 },
  { month: "June (Est.)", actual: 235.6, budget: 740 },
];

export const CATEGORY_HISTORICAL = [
  { category: "Food & Dining", April: 320, May: 280, June: 120, limit: 300 },
  { category: "Transport", April: 80, May: 95, June: 40, limit: 100 },
  { category: "Shopping", April: 150, May: 190, June: 110, limit: 150 },
  { category: "Bills", April: 50, May: 50, June: 35, limit: 60 },
  { category: "Entertainment", April: 90, May: 75, June: 22, limit: 80 },
  { category: "Other", April: 30, May: 45, June: 12, limit: 50 },
];
